name: posics-setup
channels:
  - defaults
  - conda-forge
dependencies:
  - matplotlib
  - numpy
  - pip
  - python=3.10
  - pyvisa-py
  - tk
  - tqdm
  - pip:
      - picosdk
      - pyqt5
      - pystage-apt
      - thorlabs-apt-device